<a href="https://colab.research.google.com/github/navgaur/Mathematical-Physics-III/blob/main/Integration_UGCF.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Unit-2 : Integration**


Gauss Quadrature Integration Methods: Gauss quadrature methods for integration: Gauss Legendre, Gauss Lagaurre and Gauss Hermite methods.

Recommended List of Programs:

1. Solving a definite integral by Gauss Legendre quadrature method. Application - representation of a function as a linear combination of Legendre polynomials.
2. Solving improper integrals over entire real axis or the positive real axis using Gauss Lagaurre and Gauss Hermite quadrature method. Comparison of results with the ones obtained by contour integration analytically.
3. Comparison of convergence of improper integral computed by Newton Cotes and Gauss Quadrature Methods.

---


## **Gauss-Legendre Quadratures (Gauss Quadrature)**

Generic Quadrature method works for integration of type
$$
\int_a^b f(x) dx
$$

$$
\int_{-1}^1 f(x) dx = \sum_{i-1}^n w_i f(x_i)
$$

where $w_i$ are weights and $x_i$ are quadrature points.

###**Syntax**

```
scipy.integrate.quad(func, a, b, args = (), tol = 1.49e-08, rtol = 1.49e-08, maxiter = 50, vec_func = True, miniter = 1)
```

Parameters

func: This is the Python function or the method that is being integrated.

a: This is a float value that specifies the lower limit of integration.

args: This is an optional tuple parameter. It specifies the extra arguments to be passed to the func function.

tol, rtol: This is an optional float value that defines the absolute tolerance.

**Note:** Iteration stops when the error between the last two iterates is less than tol or the relative change is less than rtol. Its default value is 1.49e-08.

maxiter: This is an optional int value that specifies the maximum order of the Gaussian quadrature.

miniter: This is an optional int value that specifies the minimum order of the Gaussian quadrature.

vec_func: This is an optional bool value that specifies True or False, if func handles arrays as arguments. The default value is True.

**Change of Range**
One can also evaluate following integration by change of range from $[a:b]$ to $[-1:1]$ by following change of variables

$$x = \frac{b-a}{2} t + \frac{b+a}{2}$$

Thus
$$\int_a^b f(x) dx = \int_{-1}^1 f\left(\frac{b-a}{2} t + \frac{b+a}{2}\right) \frac{b-a}{2} dt$$


For Gauss-Legendre Quadrature method:
 - the quadrature points ($x_i$) are zeros of Legendre Polynomails $P_i(x)$.
 - If $t_i$ are the roots of $P_n(x)$ then weights are
 $$ w_i = \frac{2}{(1 - t_i^2) [P_n'(t_i)]^2} $$

In [ ]:
from scipy.integrate import quad
import numpy as np

#f= lambda x: x**2
def func(x):
  return x**2

n = 3
nodes, weights = np.polynomial.legendre.leggauss(n)       # Calculation of Weighs and quadrature points
result = sum(weights * func(nodes))
print(nodes,weights)

print(result)

int_result= quad(func, -1, 1)
print(int_result)



[-0.77459667  0.          0.77459667] [0.55555556 0.88888889 0.55555556]
0.666666666666667
(0.6666666666666666, 7.401486830834376e-15)


## **Gauss-Lagaurre Quadrature**
$$
\int_0^\infty e^{-x} ~ f(x) dx ~~ \approx ~~ \sum_{i=1}^n w_i f(x_i)
$$


In [ ]:
from scipy.integrate import quad
import numpy as np

#f= lambda x: x**2
def func(x):
  return x**2

n = 3
nodes, weights = np.polynomial.laguerre.laggauss(n)       # Calculation of Weighs and quadrature points
result = sum(weights * func(nodes))
print(nodes,weights)

print(result)

[0.41577456 2.29428036 6.28994508] [0.71109301 0.27851773 0.01038926]
2.000000000000001


## **Gauss-Hermite Quadrature**
$$
\int_{-\infty}^\infty e^{-x^2} ~ f(x) dx ~~ \approx ~~ \sum_{i=1}^n w_i f(x_i)
$$

In [ ]:
import numpy as np

#f= lambda x: x**2
def func(x):
  return x**2

n = 3
nodes, weights = np.polynomial.hermite.hermgauss(n)       # Calculation of Weighs and quadrature points
result = sum(weights * func(nodes))
print(nodes,weights)

print(result)

[-1.22474487  0.          1.22474487] [0.29540898 1.1816359  0.29540898]
0.886226925452758


##**Expanding a function in terms of Legendre Polynomials**

$$
f(x) = \sum_{i=1}^n a_n P_n(x)
$$
where $a_n$ are the coefficients that can be found using:
$$
a_n = \frac{2n+1}{2} \int_{-1}^1 f(x) P_n(x) dx
$$

In [ ]:
import numpy as np
from scipy.special import legendre
from scipy.integrate import quad

def leg_poly(x,n):
  return legendre(n)(x)

def func(x):
  return x**2

def integrand(x,n):
  return func(x)*leg_poly(x,n)

coef=[]             # a_n values
for i in range(0,5):
  r1= ((2*i+1)/2) * quad(integrand, -1, 1, args=(i,))[0]
  coef.append(r1)

print(coef)


[0.3333333333333333, 0.0, 0.6666666666666666, -1.1055557439982511e-16, 3.688455790795686e-16]


##**Improper integrals using Gauss-Lagaurre and Gauss-Hermite method, comparing them with contour integrations**

$$
\int_0^\infty \frac{dx}{1+x^6} = \frac{\pi}{3}
$$

$$
\int_0^\infty e^{-x}x^2 dx = 2
$$

In [ ]:
from scipy.integrate import quad
import numpy as np

#f= lambda x: x**2
def func(x):
  return np.exp(x)/(1+x**6)

n = 30
nodes, weights = np.polynomial.laguerre.laggauss(n)       # Calculation of Weighs and quadrature points
result = sum(weights * func(nodes))
#print(nodes,weights)

print(result,np.pi/3)

def func1(x):
  return x**2

n=5
nodes, weights = np.polynomial.laguerre.laggauss(n)       # Calculation of Weighs and quadrature points
result1 = sum(weights * func1(nodes))
#print(nodes,weights)

print(result1,2)


1.0403253282821785 1.0471975511965976
2.0000000000000013 2


In [ ]:
import numpy as np

def func(x):
  return np.exp(x**2)/(1+x**6)

n = 20
nodes, weights = np.polynomial.hermite.hermgauss(n)       # Calculation of Weighs and quadrature points
result = sum(weights * func(nodes))
#print(nodes,weights)

print(result)

2.1002676781573038
